In [3]:
import re#Busqueda de patrones y analisis de texto
import sketch#Dibujos hechos a mano
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import geojson
import folium
from folium.plugins import HeatMap
from summarytools import dfSummary

## ETL Extracción, transformación y carga

In [14]:
#Extraemos y leemos la informacion de los dataset contemplando cuales son las hojas de calulo que necesitamos 
homicidiosHechos = pd.read_excel("homicidios.xlsx", sheet_name="HECHOS")
homicidiosVictimas = pd.read_excel("homicidios.xlsx", sheet_name="VICTIMAS")
comunas= pd.read_excel("comunas.xlsx")

## Tratamiento de los datos del dataset `homicidios - hechos`

In [15]:
homicidiosHechos

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0    2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1    2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2    2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3    2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4    2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   
..         ...         ...        ...   ...  ..  ..       ...  ..   
691  2021-0093           1 2021-12-13  2021  12  13  17:10:00  17   
692  2021-0094           1 2021-12-20  2021  12  20  01:10:00   1   
693  2021-0095           1 2021-12-30  2021  12  30  00:43:00   0   
694  2021-0096           1 2021-12-15  2021  12  15  10:30:00  10   
695  2021-0097           1 2021-11-18  2021  11  18  06:10:00   6   

                               LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...     NaN   
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...     NaN   
2                           AV ENTRE RIOS 2034       AVENIDA  ...  2034.0   
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...     NaN   
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...     NaN   
..                                         ...           ...  ...     ...   
691                          AV. RIESTRA Y MOM       AVENIDA  ...     NaN   
692                    AU DELLEPIANE Y LACARRA     AUTOPISTA  ...     NaN   
693                        AV. GAONA Y TERRADA       AVENIDA  ...     NaN   
694                         AV. EVA PERON 4071       AVENIDA  ...  4071.0   
695                    PADRE CARLOS MUJICA 709         CALLE  ...   709.0   

                                   Cruce  \
0    FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                    DE LOS CORRALES AV.   
2                                    NaN   
3               VILLEGAS, CONRADO, GRAL.   
4                SAENZ PE?A, LUIS, PRES.   
..                                   ...   
691                                  MOM   
692                          LACARRA AV.   
693                              TERRADA   
694                                  NaN   
695                                  NaN   

                                 Dirección Normalizada COMUNA  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                  ENTRE RIOS AV. 2034      1   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   
..                                                 ...    ...   
691                                  RIESTRA AV. y MOM      7   
692         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.      9   
693                                GAONA AV. y TERRADA     11   
694                                PERON, EVA AV. 4071      9   
695                            PADRE CARLOS MUGICA 709      1   

                                   XY (CABA)         pos x         pos y  \
0      Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1      Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2     Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3      Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4    Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   
..                                       ...           ...           ...   
691   Point (102728.60090138 98186.24929177)  -58.43353773  -34.64561636   
692    Point (99624.29795829 97569.69801131)  -58.46739825  -34.65117757   
693   Point (99116.45492358 101045.23284826)  -58.47293407  -34.61984745   
694    Point (99324.54463985 97676.26932409)  -58.47066794  -34.65021673   
695  Point (107664.16647795 104708.63962087)  -58.37976155  -34.58679619   

      PARTICIPANTES    VICTIMA    A

In [16]:
#Verificamos si existen datos nulos o duplicados 
homicidiosHechos.isnull().sum()

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       0
HH                         0
LUGAR_DEL_HECHO            0
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    0
ACUSADO                    0
dtype: int64

In [17]:
homicidiosHechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Altura                 129 non-null    float64       
 12  Cruce                  525 non-null    object        
 13  Direc

In [18]:
homicidiosHechos[homicidios_hechos["Dirección Normalizada"].isnull()][["Dirección Normalizada", "Cruce","Altura", "Calle"]]

Dirección Normalizada Cruce  Altura                                 Calle
38                    NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
106                   NaN   NaN     NaN     AUTOPISTA BUENOS AIRES - LA PLATA
119                   NaN   NaN     NaN                                   NaN
180                   NaN   NaN     NaN               AUTOPISTA PERITO MORENO
181                   NaN   NaN     NaN  AUTOPISTA DELLEPIANE LUIS TTE. GRAL.
313                   NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
546                   NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
621                   NaN   NaN     NaN     AUTOPISTA BUENOS AIRES - LA PLATA

In [19]:
homicidiosHechos[["Altura", "Calle", "Dirección Normalizada", "Cruce"]][:5]

Altura             Calle  \
0     NaN  PIEDRA BUENA AV.   
1     NaN    PAZ, GRAL. AV.   
2  2034.0    ENTRE RIOS AV.   
3     NaN    LARRAZABAL AV.   
4     NaN      SAN JUAN AV.   

                               Dirección Normalizada  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                ENTRE RIOS AV. 2034   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   

                                 Cruce  
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.  
1                  DE LOS CORRALES AV.  
2                                  NaN  
3             VILLEGAS, CONRADO, GRAL.  
4              SAENZ PE?A, LUIS, PRES.

Nuestro DataFrame consta de 696 filas con 21 columnas cada una, esto para un total de 14,616 datos, de estos, 747 son datos nulos pertenecientes a las columnas: **`Altura`**, **`Dirección Normalizada`**, **`Cruce`** y **`Calle`**. 
- Para el caso de **`Calle`** tiene un solo dato nulo.
- Para el caso de  **`Dirección Normalizada`** 8 nulos. 
- Para el caso de **`Cruce`** tiene 171 nulos, siendo el 24.56% del los datos de la columna.
- Para el caso de **`Altura`** tiene 567 nulos que representan el 81.5% de datos de la columna

La razon por la que la columna `Altura` carece de tantos datos es debido a que esta hace referencia al punto en que en una avenida o calle sucede un siniestro y dado que una gran cantidad de los mismos sucede en cruces o intersecciones es muy comun que no se tenga la infomación disponible.

La columna `Cruce` solo va a tener dato cuando el hecho se porduce en un cruce de calles, por lo que se conserva de esta manera.
La columna `Dirección Normalizada` no tiene posibilidad de completarse con las columnas del dataset; pero contiene solo 1,1% de nulos por lo se conserva de esta manera.
 

In [20]:
# Se elimina la columna "Altura"
homicidiosHechos= homicidiosHechos.drop("Altura", axis=1)
homicidiosHechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

In [21]:
homicidiosHechos.duplicated().sum()

0

### Transformación de datos

Con el proposito de mejorar la versatilidad de los datos y su mosterior manipulación la columna `HH`pasara de ser tipo object a int, esto con el proposito de permitir su modificación posterior.


In [22]:
#Eliminando datos duplicados

homicidiosHechos["HH"].unique()

array([4, 1, 7, 0, 5, 18, 19, 15, 11, 22, 16, 9, 23, 6, 10, 17, 12, 8, 20,
       21, 14, 3, 2, 13, 'SD'], dtype=object)

El dato SD por ahora lo mantendremos asi dado que en caso de ser eliminado podria ser perjudicial para nuestra muestra de datos SD, no contemplamos la idea de promediar el resto de datos y suplirlo ya que podria no ser representativo.

In [23]:
# Con el proposito de poder manipular la columna HH se hacen los cambios necesarios para que sea de tipo Int64 
homicidiosHechos["HH"] = pd.to_numeric(homicidiosHechos ["HH"], errors="coerce")
homicidiosHechos["HH"] = homicidiosHechos["HH"].astype("Int64")

In [24]:
# Filtrar filas con posiciones no válidas
valid_positions = ~(homicidiosHechos['pos x'].str.contains('[^0-9.,-]') | homicidiosHechos['pos y'].str.contains('[^0-9.,-]') | (homicidiosHechos['pos x'] == '.') | (homicidiosHechos['pos y'] == '.'))

# Establecer posiciones no válidas en NaN
homicidiosHechos.loc[~valid_positions, ['pos x', 'pos y']] = np.nan

# Convertir las cadenas a tipo numérico (float)
homicidiosHechos['pos x'] = homicidiosHechos['pos x'].str.replace(',', '.').astype(float)
homicidiosHechos['pos y'] = homicidiosHechos['pos y'].str.replace(',', '.').astype(float)

In [25]:
homicidiosHechos.head(3)

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             Calle  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  PIEDRA BUENA AV.   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ    PAZ, GRAL. AV.   
2                         AV ENTRE RIOS 2034       AVENIDA    ENTRE RIOS AV.   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   

                               Dirección Normalizada  COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...       8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.       9   
2                                ENTRE RIOS AV. 2034       1   

                                XY (CABA)      pos x      pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS  
2       MOTO-AUTO    MOTO       AUTO

In [26]:
#La columna `XY (CABA)` posee coordenadas para poder ubicar en un mapa , las extraemos para poder utilizar


def extraer_coordenadas(texto):
    # Utilizamos una expresión regular para extraer las coordenadas
    coordenadas = re.findall(r'\d+\.\d+', texto)
    if len(coordenadas) == 2:
        return float(coordenadas[0]), float(coordenadas[1])
    else:
        return None, None

# Aplicar la función a la columna 'XY (CABA)'
homicidiosHechos ['coordenada_x'], homicidiosHechos['coordenada_y'] = zip(*homicidiosHechos['XY (CABA)'].map(extraer_coordenadas))

# Filtrar los registros que no tienen coordenadas válidas
homicidios_hechos = homicidiosHechos[(homicidiosHechos['coordenada_x'].notnull()) & (homicidiosHechos['coordenada_y'].notnull())]



In [28]:
#verficamos los cambios realizados:

homicidiosHechos.head()

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3  2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4  2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...   
2                         AV ENTRE RIOS 2034       AVENIDA  ...   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...   

                               Dirección Normalizada COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                ENTRE RIOS AV. 2034      1   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   

                                 XY (CABA)      pos x      pos y  \
0    Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1    Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2   Point (106684.29090040 99706.57687843) -58.390403 -34.631894   
3    Point (99840.65224780 94269.16534422) -58.465039 -34.680930   
4  Point (106980.32827929 100752.16915795) -58.387183 -34.622466   

    PARTICIPANTES  VICTIMA    ACUSADO   coordenada_x   coordenada_y  
0       MOTO-AUTO     MOTO       AUTO   98896.782384   93532.434378  
1  AUTO-PASAJEROS     AUTO  PASAJEROS   95832.055711   95505.416420  
2       MOTO-AUTO     MOTO       AUTO  106684.290900   99706.576878  
3         MOTO-SD     MOTO         SD   99840.652248   94269.165344  
4  MOTO-PASAJEROS     MOTO  PASAJEROS  106980.328279  100752.169158  

[5 rows x 22 columns]

In [30]:
#Observemos lo cambios en las columnas 
homicidiosHechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO', 'coordenada_x', 'coordenada_y'],
      dtype='object')

A modo de una buena practica vamos a estandarizar ls mayusculas y minusculas de las columnas:

In [31]:
#Cambio la primer letra a mayúscula
homicidiosHechos.columns = [x.capitalize() for x in homicidiosHechos.columns]
# Reemplazo guiones por espacios
homicidiosHechos.columns = homicidiosHechos.columns.str.replace("_", " ")
#Renombra columnas 
homicidiosHechos= homicidiosHechos.rename(columns={"N victimas": "Num víctimas",
                                            "Aaaa": "Año",
                                            "Mm":"Mes",
                                            "Dd": "Día",
                                            "Hora": "Hora completa",
                                            "Hh": "Hora"}) 

homicidiosHechos.columns

Index(['Id', 'Num víctimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora completa',
       'Hora', 'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Xy (caba)', 'Pos x', 'Pos y',
       'Participantes', 'Victima', 'Acusado', 'Coordenada x', 'Coordenada y'],
      dtype='object')

Voy a realizar un analisis de la columna `Día` esto debido a que si lo analizamos en funcion de ello podriamos establecer mediante los `Días semanas` si existe un incremento o decremento en función de si es o no fin de semana.

In [33]:
#Consulto la columna Día
homicidiosHechos.Día

0       1
1       2
2       3
3      10
4      21
       ..
691    13
692    20
693    30
694    15
695    18
Name: Día, Length: 696, dtype: int64

In [35]:
#Creo una columna nueva `Día semana` que contenga el nombre del día de la semana
homicidiosHechos['Día semana'] = homicidiosHechos['Fecha'].dt.strftime('%A')

#Creo un diccionario para modificar a español los nombres de los dás de la semana y lo aplico a la columna nueva
dic={  'Friday':'Viernes',
       'Saturday': 'Sabado',
       'Sunday': 'Domingo',  
       'Thursday': 'Jueves',
        'Monday': 'Lunes',
        'Wednesday': 'Miercoles',
       'Tuesday': 'Martes'}
homicidiosHechos['Día semana'] =homicidiosHechos['Día semana'].replace(dic)

homicidiosHechos.head()

Id  Num víctimas      Fecha   Año  Mes  Día Hora completa  Hora  \
0  2016-0001             1 2016-01-01  2016    1    1      04:00:00     4   
1  2016-0002             1 2016-01-02  2016    1    2      01:15:00     1   
2  2016-0003             1 2016-01-03  2016    1    3      07:00:00     7   
3  2016-0004             1 2016-01-10  2016    1   10      00:00:00     0   
4  2016-0005             1 2016-01-21  2016    1   21      05:20:00     5   

                             Lugar del hecho Tipo de calle  ... Comuna  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...      8   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...      9   
2                         AV ENTRE RIOS 2034       AVENIDA  ...      1   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...      8   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...      1   

                                 Xy (caba)      Pos x      Pos y  \
0    Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1    Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2   Point (106684.29090040 99706.57687843) -58.390403 -34.631894   
3    Point (99840.65224780 94269.16534422) -58.465039 -34.680930   
4  Point (106980.32827929 100752.16915795) -58.387183 -34.622466   

    Participantes  Victima    Acusado   Coordenada x   Coordenada y Día semana  
0       MOTO-AUTO     MOTO       AUTO   98896.782384   93532.434378    Viernes  
1  AUTO-PASAJEROS     AUTO  PASAJEROS   95832.055711   95505.416420     Sabado  
2       MOTO-AUTO     MOTO       AUTO  106684.290900   99706.576878    Domingo  
3         MOTO-SD     MOTO         SD   99840.652248   94269.165344    Domingo  
4  MOTO-PASAJEROS     MOTO  PASAJEROS  106980.328279  100752.169158     Jueves  

[5 rows x 23 columns]

In [37]:
homicidiosHechos["Comuna"].unique()

array([ 8,  9,  1, 11, 15,  4,  7, 12,  3, 13, 14, 10,  6,  2,  5,  0],
      dtype=int64)

In [39]:
#Agrego la palabra Comuna delante del dato numérico
#se aplica la función lambda a cada fila del dataframe 
homicidiosHechos["Comuna"] = homicidiosHechos.apply(lambda x: "Comuna "+str(x["Comuna"]), axis=1)

homicidiosHechos["Comuna"].unique()

array(['Comuna Comuna 8', 'Comuna Comuna 9', 'Comuna Comuna 1',
       'Comuna Comuna 11', 'Comuna Comuna 15', 'Comuna Comuna 4',
       'Comuna Comuna 7', 'Comuna Comuna 12', 'Comuna Comuna 3',
       'Comuna Comuna 13', 'Comuna Comuna 14', 'Comuna Comuna 10',
       'Comuna Comuna 6', 'Comuna Comuna 2', 'Comuna Comuna 5',
       'Comuna Comuna 0'], dtype=object)

Se realiza un resumen descriptivo de los datos en `homicidios-hechos`

In [40]:
dfSummary(homicidiosHechos)

## Tratamiento de los datos del dataset `homicidios- víctimas`

In [41]:
homicidiosVictimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_hecho             717 non-null    object        
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64         
 3   MM                   717 non-null    int64         
 4   DD                   717 non-null    int64         
 5   ROL                  717 non-null    object        
 6   VICTIMA              717 non-null    object        
 7   SEXO                 717 non-null    object        
 8   EDAD                 717 non-null    object        
 9   FECHA_FALLECIMIENTO  717 non-null    object        
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB


### Transformación de los datos

Conversión del tipo de dato

In [43]:
#Cambio la columna a tipo datetime
homicidiosVictimas["FECHA_FALLECIMIENTO"] = pd.to_datetime(homicidiosVictimas["FECHA_FALLECIMIENTO"], format='%Y-%m-%d', errors='coerce')

In [44]:
#Una vez que se paso el tipo de dato a datetime que es una fecha y hora completa se utiliza este codigo para que solo se quede en formato fecha sin hora
homicidiosVictimas["FECHA_FALLECIMIENTO"] = homicidiosVictimas["FECHA_FALLECIMIENTO"].dt.date

#Luego se reemplazan las fechas en cero con espacios vacios a fin de su manipulación
homicidiosVictimas["FECHA_FALLECIMIENTO"] = homicidiosVictimas ["FECHA_FALLECIMIENTO"].replace(pd.NaT,"")

In [45]:
#Cambio la columna edad a numerico y luego a tipo entero
homicidiosVictimas["EDAD"] = pd.to_numeric(homicidiosVictimas["EDAD"], errors="coerce")
homicidiosVictimas["EDAD"] = homicidiosVictimas["EDAD"].astype("Int64")

In [46]:
#Utilizo Numpy para reemplazar por NaN los sin datos o vacios y luego paso a float para que cuando quiera aplicar estadisticas no tenga errores debido a esos datos
homicidiosVictimas["EDAD"] = homicidiosVictimas["EDAD"].replace([" ","SD"], np.nan)

In [47]:
homicidiosVictimas["EDAD"] = homicidiosVictimas["EDAD"].fillna(0.0)

In [48]:
#Controlo los datos de la columna
homicidiosVictimas ["EDAD"].unique()

<IntegerArray>
[19, 70, 30, 18, 29, 22, 16, 59, 65, 34, 41, 50, 38, 21, 52, 36, 20, 54,  0,
 56, 24, 78, 79, 26, 57, 37, 58, 23, 60, 42, 53, 51, 40, 87, 76, 75, 35, 80,
 43, 45, 67, 27, 55, 49, 81, 25, 33, 46, 83, 39, 28,  7, 48,  4, 82, 32, 17,
 47, 61, 10, 95, 73, 84, 66, 85,  1, 15, 13, 77, 44, 31, 62, 74, 71, 11, 86,
 69, 72, 12, 63, 92, 68, 91, 64,  5, 88]
Length: 86, dtype: Int64

In [49]:
homicidiosVictimas.head(3)

ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30   

  FECHA_FALLECIMIENTO  
0          2016-01-01  
1          2016-01-02  
2          2016-01-03

In [50]:
homicidiosVictimas.isnull().sum()

ID_hecho               0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

No se encuentran datos nulos, ni campos vacios

Se crea la columna `Rango etario` basada en la columna `Edad`, para mejorar el análisis de los datos 

In [51]:

# Se utiliza la función `pd.cut()`, que permite agrupar valores numéricos en intervalos o categorías


# Definir los límites de los rangos etarios y las etiquetas
bins = [0, 20, 40, 60, 80, 100]
labels = ['Menos de 20', ' Entre 21- 40', 'Entre 41-60', 'Entre 61-80', 'Más de 80']

# Utilizar pd.cut() para crear la columna de rango etario
homicidiosVictimas['Rango_etario'] = pd.cut(homicidiosVictimas['EDAD'], bins=bins, labels=labels, right=False)

homicidiosVictimas.head(3)

ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30   

  FECHA_FALLECIMIENTO   Rango_etario  
0          2016-01-01    Menos de 20  
1          2016-01-02    Entre 61-80  
2          2016-01-03   Entre 21- 40

A continuación se estandarizan las mayúsculas y minúsculas del dataset

In [52]:
# Se coloca la primera en mayúscula
homicidiosVictimas.columns = [x.capitalize() for x in homicidiosVictimas.columns]
# Se reemplazan los guiones por espacios
homicidiosVictimas.columns = homicidiosVictimas.columns.str.replace('_', ' ')
# Se renombran algunas columnas
homicidiosVictimas = homicidiosVictimas.rename(columns={'Id hecho': 'Id',
                                                      'Aaaa':'Año',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Victima':'Víctima'})
homicidiosVictimas.columns

Index(['Id', 'Fecha', 'Año', 'Mes', 'Día', 'Rol', 'Víctima', 'Sexo', 'Edad',
       'Fecha fallecimiento', 'Rango etario'],
      dtype='object')

A partir de los datos, se analiza eliminar columnas que se repiten en ambos dataset para realizar luego la unión y trabajar con un conjunto de datos.
Se proceden a eliminar del dataset `homicidios_victimas` las columnas `Fecha`, `Año`, `Mes`, `Día` y `Victima` que contienen la misma información que se encuentra en `homicidios_hechos`. 

In [53]:
#Se busca un registro para comparar con el mismo registro en el otro dataset
homicidiosHechos[homicidiosHechos["Id"]=="2019-0012"]

Id  Num víctimas      Fecha   Año  Mes  Día Hora completa  Hora  \
429  2019-0012             1 2019-02-17  2019    2   17      03:16:00     3   

                        Lugar del hecho Tipo de calle  ...           Comuna  \
429  CASTAÑARES AV. Y GORDILLO, TIMOTEO       AVENIDA  ...  Comuna Comuna 8   

                                 Xy (caba)      Pos x      Pos y  \
429  Point (98072.98959434 94742.80804806) -58.484327 -34.676658   

    Participantes  Victima  Acusado  Coordenada x  Coordenada y Día semana  
429     MOTO-AUTO     MOTO     AUTO  98072.989594  94742.808048    Domingo  

[1 rows x 23 columns]

In [54]:
homicidiosVictimas[homicidiosVictimas["Id"]=="2019-0012"]

Id      Fecha   Año  Mes  Día        Rol Víctima       Sexo  Edad  \
447  2019-0012 2019-02-17  2019    2   17  CONDUCTOR    MOTO  MASCULINO    31   

    Fecha fallecimiento   Rango etario  
447          2019-02-20   Entre 21- 40

In [55]:
dfSummary(homicidiosVictimas)

In [56]:
# Se eliminan las columnas repetidas
homicidiosVictimas = homicidiosVictimas.drop(['Fecha', 'Año', 'Mes', 'Día', 'Víctima'], axis=1)
homicidiosVictimas.columns

Index(['Id', 'Rol', 'Sexo', 'Edad', 'Fecha fallecimiento', 'Rango etario'], dtype='object')

## Unificación de los dataset

Por medio de la función merge se unifican los dataset transformados anteriormente

In [57]:
siniestros= homicidiosVictimas.merge(homicidiosHechos, on="Id", how="left")
siniestros.columns

Index(['Id', 'Rol', 'Sexo', 'Edad', 'Fecha fallecimiento', 'Rango etario',
       'Num víctimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora completa', 'Hora',
       'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Xy (caba)', 'Pos x', 'Pos y',
       'Participantes', 'Victima', 'Acusado', 'Coordenada x', 'Coordenada y',
       'Día semana'],
      dtype='object')

In [58]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Id                     717 non-null    object        
 1   Rol                    717 non-null    object        
 2   Sexo                   717 non-null    object        
 3   Edad                   717 non-null    Int64         
 4   Fecha fallecimiento    717 non-null    object        
 5   Rango etario           717 non-null    category      
 6   Num víctimas           717 non-null    int64         
 7   Fecha                  717 non-null    datetime64[ns]
 8   Año                    717 non-null    int64         
 9   Mes                    717 non-null    int64         
 10  Día                    717 non-null    int64         
 11  Hora completa          717 non-null    object        
 12  Hora                   716 non-null    Int64         
 13  Lugar

In [59]:
siniestros["Num víctimas"].unique()

array([1, 2, 3], dtype=int64)

In [60]:
siniestros ["Num víctimas"] = siniestros ["Num víctimas"].fillna(0.0)
siniestros ["Num víctimas"] = siniestros ["Num víctimas"].astype ("Int64")

In [61]:
siniestros["Num víctimas"].unique()

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [62]:
siniestros["Año"].unique()

array([2016, 2017, 2018, 2019, 2020, 2021], dtype=int64)

In [63]:
siniestros ["Año"]= siniestros ["Año"].astype ("Int64")
siniestros["Año"].unique()

<IntegerArray>
[2016, 2017, 2018, 2019, 2020, 2021]
Length: 6, dtype: Int64

In [64]:
siniestros ["Mes"]= siniestros ["Mes"].astype ("Int64")
siniestros["Mes"].unique()

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Length: 12, dtype: Int64

In [65]:
siniestros ["Día"]= siniestros ["Día"].astype ("Int64")
siniestros["Día"].unique()

<IntegerArray>
[ 1,  2,  3, 10, 21, 24, 29,  8, 14, 15, 17, 28,  4, 12, 13, 19, 23, 30, 31,
 11, 20, 22, 25, 26, 16, 18, 27,  7,  9,  5,  6]
Length: 31, dtype: Int64

In [66]:
siniestros.head(3)

Id        Rol       Sexo  Edad Fecha fallecimiento   Rango etario  \
0  2016-0001  CONDUCTOR  MASCULINO    19          2016-01-01    Menos de 20   
1  2016-0002  CONDUCTOR  MASCULINO    70          2016-01-02    Entre 61-80   
2  2016-0003  CONDUCTOR  MASCULINO    30          2016-01-03   Entre 21- 40   

   Num víctimas      Fecha   Año  Mes  ...           Comuna  \
0             1 2016-01-01  2016    1  ...  Comuna Comuna 8   
1             1 2016-01-02  2016    1  ...  Comuna Comuna 9   
2             1 2016-01-03  2016    1  ...  Comuna Comuna 1   

                                Xy (caba)      Pos x      Pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    Participantes Victima    Acusado   Coordenada x  Coordenada y Día semana  
0       MOTO-AUTO    MOTO       AUTO   98896.782384  93532.434378    Viernes  
1  AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711  95505.416420     Sabado  
2       MOTO-AUTO    MOTO       AUTO  106684.290900  99706.576878    Domingo  

[3 rows x 28 columns]

In [68]:
siniestros.describe()

Edad  Num víctimas                          Fecha          Año  \
count      717.0         717.0                            717        717.0   
mean   39.050209      1.061367  2018-09-09 01:24:21.087866112  2018.174338   
min          0.0           1.0            2016-01-01 00:00:00       2016.0   
25%         24.0           1.0            2017-04-01 00:00:00       2017.0   
50%         35.0           1.0            2018-07-07 00:00:00       2018.0   
75%         55.0           1.0            2019-12-18 00:00:00       2019.0   
max         95.0           3.0            2021-12-30 00:00:00       2021.0   
std    22.010669      0.257024                            NaN     1.672655   

            Mes        Día       Hora       Pos x       Pos y   Coordenada x  \
count     717.0      717.0      716.0  704.000000  704.000000     702.000000   
mean   6.688982  15.953975  11.554469  -58.441664  -34.619700  101980.113004   
min         1.0        1.0        0.0  -58.529942  -34.705250   93889.867899   
25%         4.0        9.0        6.0  -58.476556  -34.643918   98744.378735   
50%         7.0       16.0       11.0  -58.444513  -34.622866  101721.590022   
75%        10.0       23.0       17.0  -58.401841  -34.597013  105630.884244   
max        12.0       31.0       23.0  -58.356082  -34.534654  109831.098614   
std     3.57514   8.674876   6.700055    0.046397    0.035292    4253.717694   

        Coordenada y  
count     702.000000  
mean   101070.596233  
min     91571.233073  
25%     98387.965943  
50%    100711.696729  
75%    103582.742374  
max    110496.053085  
std      3914.938863

In [69]:
dfSummary(siniestros)

In [78]:
#Creo una lista con el orden 
nuevoOrden=["Id", "Fecha", "Año", "Mes", "Día","Día semana", "Hora completa", "Hora", "Num víctimas", "Participantes", "Rol", "Acusado", "Victima", "Sexo", "Edad", "Rango etario", "Fecha fallecimiento", "Lugar del hecho", "Tipo de calle", "Calle", "Cruce", "Dirección normalizada", "Comuna", "Xy (caba)", "Coordenada x", "Coordenada y", "Pos x", "Pos y"]

#Reorganizo el dataframe untilizando la lista y asignandola nuevamente aldataframe siniestros
siniestrosLimpio = siniestros[nuevoOrden]
siniestrosLimpio.columns


Index(['Id', 'Fecha', 'Año', 'Mes', 'Día', 'Día semana', 'Hora completa',
       'Hora', 'Num víctimas', 'Participantes', 'Rol', 'Acusado', 'Victima',
       'Sexo', 'Edad', 'Rango etario', 'Fecha fallecimiento',
       'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Xy (caba)', 'Coordenada x',
       'Coordenada y', 'Pos x', 'Pos y'],
      dtype='object')

In [79]:
siniestrosLimpio.head(3)

Id      Fecha   Año  Mes  Día Día semana Hora completa  Hora  \
0  2016-0001 2016-01-01  2016    1    1    Viernes      04:00:00     4   
1  2016-0002 2016-01-02  2016    1    2     Sabado      01:15:00     1   
2  2016-0003 2016-01-03  2016    1    3    Domingo      07:00:00     7   

   Num víctimas   Participantes  ... Tipo de calle             Calle  \
0             1       MOTO-AUTO  ...       AVENIDA  PIEDRA BUENA AV.   
1             1  AUTO-PASAJEROS  ...      GRAL PAZ    PAZ, GRAL. AV.   
2             1       MOTO-AUTO  ...       AVENIDA    ENTRE RIOS AV.   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   

                               Dirección normalizada           Comuna  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...  Comuna Comuna 8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.  Comuna Comuna 9   
2                                ENTRE RIOS AV. 2034  Comuna Comuna 1   

                                Xy (caba)   Coordenada x  Coordenada y  \
0   Point (98896.78238426 93532.43437792)   98896.782384  93532.434378   
1   Point (95832.05571093 95505.41641999)   95832.055711  95505.416420   
2  Point (106684.29090040 99706.57687843)  106684.290900  99706.576878   

       Pos x      Pos y  
0 -58.475340 -34.687570  
1 -58.508775 -34.669777  
2 -58.390403 -34.631894  

[3 rows x 28 columns]

In [81]:
siniestrosLimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Id                     717 non-null    object        
 1   Fecha                  717 non-null    datetime64[ns]
 2   Año                    717 non-null    Int64         
 3   Mes                    717 non-null    Int64         
 4   Día                    717 non-null    Int64         
 5   Día semana             717 non-null    object        
 6   Hora completa          717 non-null    object        
 7   Hora                   716 non-null    Int64         
 8   Num víctimas           717 non-null    Int64         
 9   Participantes          717 non-null    object        
 10  Rol                    717 non-null    object        
 11  Acusado                717 non-null    object        
 12  Victima                717 non-null    object        
 13  Sexo 

In [82]:
siniestrosLimpio["Fecha"]=siniestrosLimpio["Fecha"].dt.date

In [83]:
siniestrosLimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   Id                     717 non-null    object  
 1   Fecha                  717 non-null    object  
 2   Año                    717 non-null    Int64   
 3   Mes                    717 non-null    Int64   
 4   Día                    717 non-null    Int64   
 5   Día semana             717 non-null    object  
 6   Hora completa          717 non-null    object  
 7   Hora                   716 non-null    Int64   
 8   Num víctimas           717 non-null    Int64   
 9   Participantes          717 non-null    object  
 10  Rol                    717 non-null    object  
 11  Acusado                717 non-null    object  
 12  Victima                717 non-null    object  
 13  Sexo                   717 non-null    object  
 14  Edad                   717 non-null    Int

In [84]:
dfSummary(siniestrosLimpio, is_collapsible=True)

In [86]:
siniestrosLimpio.to_csv("siniestosLimpio.csv", index=False)